name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-22.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb x11-utils

      - name: Run tests
        run: xvfb-run lde test
